# Generated by Django 6.0 on 2025-12-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='The exact text from the resume')),
                ('optimized_text', models.TextField(help_text='The AI rewritten version')),
                ('reason', models.TextField(help_text="Why this change was made (e.g. 'Aligned with JD terminology')")),
                ('category', models.CharField(default='Terminology', max_length=50)),
                ('match_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.matchresult')),
            ],
        ),
    ]
